name: vsproject
description: A startup-namer app.
version: 1.0.0+1

# #docregion dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  google_maps_flutter: ^0.4.0

# #enddocregion dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
